version: '3.8'  # Docker Compose version

services:
  postgres:  # Name of the service (can be changed)
    image: postgres:15-alpine  # Uses lightweight Alpine Linux version of Postgres 15
    container_name: topalbums-postgres
    environment:
      POSTGRES_DB: topalbumsdb         # The database to create
      POSTGRES_USER: leela             # The DB username
      POSTGRES_PASSWORD: password      # The DB password
    ports:
      - "5432:5432"  # Maps port 5432 in container → 5432 on my machine
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persists data in a named volume

volumes:
  pgdata:  # Named volume that Docker will manage (so your data isn't lost when the container stops)
